#arch: ppc64le (not required when deploying on power vm)
os: linux-ppc64le
dist: bionic

script: 
  - arch
  - df -h
  - free -h
  - ifconfig
  - sudo apt-get update -y
  - sudo apt-get install gimp -y  
  
  

